#include<stdlib.h>
#include<stdio.h>
#include<string.h>
main(){
	int countA=0,countB=0,countC=0;
	int x,i;
	scanf("%d",&x);
	char a[x];
		scanf("%s",&a);
	for(i=1;i<=(x/6)+1;i++){
		if(a[12*(i-1)]==65){
			countA=countA+1;
			countB=countB;
			countC=countC;
		}
		if(a[12*(i-1)+1]==65){
			countA=countA;
			countB=countB+1;
			countC=countC;
		}
		if(a[12*(i-1)+2]==65){
			countA=countA;
			countB=countB;
			countC=countC+1;		
		}
		if(a[12*(i-1)+3]==65){
			countA=countA+1;
			countB=countB;
			countC=countC+1;
		}
		if(a[12*(i-1)+4]==65){
			countA=countA;
			countB=countB;
			countC=countC;
		}
		if(a[12*(i-1)+5]==65){
			countA=countA;
			countB=countB+1;
			countC=countC;
		}
		if(a[12*(i-1)+6]==65){
			countA=countA+1;
			countB=countB;
			countC=countC;
		}
		if(a[12*(i-1)+7]==65){
			countA=countA;
			countB=countB;
			countC=countC;
		}
		if(a[12*(i-1)+8]==65){
			countA=countA;
			countB=countB;
			countC=countC+1;
		}
		if(a[12*(i-1)+9]==65){
			countA=countA+1;
			countB=countB+1;
			countC=countC+1;
		}
		if(a[12*(i-1)+10]==65){
			countA=countA;
			countB=countB;
			countC=countC;
		}
		if(a[12*(i-1)+11]==65){
			countA=countA;
			countB=countB;
			countC=countC;
		}
		//B
		
		if(a[12*(i-1)]==66){
			countA=countA;
			countB=countB+1;
			countC=countC;
		}
		if(a[12*(i-1)+1]==66){
			countA=countA+1;
			countB=countB;
			countC=countC;
		}
		if(a[12*(i-1)+2]==66){
			countA=countA;
			countB=countB+1;
			countC=countC;		
		}
		if(a[12*(i-1)+3]==66){
			countA=countA;
			countB=countB;
			countC=countC;
		}
		if(a[12*(i-1)+4]==66){
			countA=countA+1;
			countB=countB+1;
			countC=countC+1;
		}
		if(a[12*(i-1)+5]==66){
			countA=countA;
			countB=countB;
			countC=countC+1;
		}
		if(a[12*(i-1)+6]==66){
			countA=countA;
			countB=countB+1;
			countC=countC;
		}
		if(a[12*(i-1)+7]==66){
			countA=countA+1;
			countB=countB;
			countC=countC;
		}
		if(a[12*(i-1)+8]==66){
			countA=countA;
			countB=countB+1;
			countC=countC;
		}
		if(a[12*(i-1)+9]==66){
			countA=countA;
			countB=countB;
			countC=countC;
		}
		if(a[12*(i-1)+10]==66){
			countA=countA+1;
			countB=countB+1;
			countC=countC+1;
		}
		if(a[12*(i-1)+11]==66){
			countA=countA;
			countB=countB;
			countC=countC+1;
		}
		
		//C
		
		if(a[12*(i-1)]==67){
			countA=countA;
			countB=countB;
			countC=countC+1;
		}
		if(a[12*(i-1)+1]==67){
			countA=countA;
			countB=countB;
			countC=countC+1;
		}
		if(a[12*(i-1)+2]==67){
			countA=countA+1;
			countB=countB;
			countC=countC;		
		}
		if(a[12*(i-1)+3]==67){
			countA=countA;
			countB=countB+1;
			countC=countC;
		}
		if(a[12*(i-1)+4]==67){
			countA=countA;
			countB=countB;
			countC=countC;
		}
		if(a[12*(i-1)+5]==67){
			countA=countA+1;
			countB=countB;
			countC=countC;
		}
		if(a[12*(i-1)+6]==67){
			countA=countA;
			countB=countB;
			countC=countC+1;
		}
		if(a[12*(i-1)+7]==67){
			countA=countA;
			countB=countB+1;
			countC=countC+1;
		}
		if(a[12*(i-1)+8]==67){
			countA=countA+1;
			countB=countB;
			countC=countC;
		}
		if(a[12*(i-1)+9]==67){
			countA=countA;
			countB=countB;
			countC=countC;
		}
		if(a[12*(i-1)+10]==67){
			countA=countA;
			countB=countB;
			countC=countC;
		}
		if(a[12*(i-1)+11]==67){
			countA=countA+1;
			countB=countB+1;
			countC=countC;
		}
		
		
		
	}
	if(countA==countB&&countB==countC){
		printf("%d\n",countA);
		printf("Adrian\nBruno\nGoran");
	}
	else if(countA==countB){
		if(countB>countC){
			printf("%d",countA);
			printf("\nAdrian\nBruno");
		}else{
			printf("%d",countC);
			printf("\nGoran");
		}
	}
	else if(countA==countC){
		if(countA>countB){
			printf("%d",countA);
			printf("\nAdrian\nGoran");
		}else{
			printf("%d",countB);
			printf("\nBruno");
		}
	}
	else if(countB==countC){
		if(countA>countC){
			printf("%d",countA);
			printf("\nAdrian");
		}else{
			printf("%d",countB);
			printf("\nBruno\nGoran");
		}
	}
	else if(countA>countB){
		if(countB>countC){
			printf("%d\n",countA);
			printf("Adrian");
		}
		else{
			if(countA<countC){
				printf("%d\n",countC);
				printf("Goran");
			}
			else{
				printf("%d\n",countA);
				printf("Adrian");
			}
		}	
	}
	else if(countA<countB){
		if(countA>countC){
			printf("%d\n",countB);
			printf("Bruno");
		}
		else{
			if(countB>countC){
				printf("%d\n",countB);
				printf("Bruno");
			}
			else{
				printf("%d\n",countC);
				printf("Goran");
			}
		}	
	}
}
